// Code Generated by Sidekick is for learning and experimentation purposes only.
const express = require('express');
const bodyParser = require('body-parser');
const { broadcast } = require('./websocket-server');
const { Client } = require('pg'); // Assuming PostgreSQL

const app = express();
app.use(bodyParser.json());

const client = new Client({
  connectionString: process.env.DATABASE_URL,
});
client.connect();

app.post('/update-status', async (req, res) => {
  const statusUpdate = req.body;

  try {
    // Update the database
    await client.query('UPDATE status_table SET status = $1 WHERE id = $2', [statusUpdate.status, statusUpdate.id]);

    // Notify WebSocket clients
    broadcast(statusUpdate);

    res.sendStatus(200);
  } catch (error) {
    console.error('Error updating status:', error);
    res.sendStatus(500);
  }
});

app.listen(3000, () => {
  console.log('API server listening on port 3000');
});
